--CREATE DATABASE GTS
USE GTS

CREATE TABLE PERSON(
	PERSON_ID INT NOT NULL,
	PERSON_FNAME VARCHAR(50) NOT NULL,
	PERSON_LNAME VARCHAR(50) NOT NULL,
	PRIMARY KEY (PERSON_ID),
	CONSTRAINT NL UNIQUE (PERSON_FNAME, PERSON_LNAME))

CREATE TABLE UNIVERSITY(
	UNIVERSITY_NAME VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY (UNIVERSITY_NAME))

CREATE TABLE SUBJECT_TOPIC(
	TOPIC_NAME VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY(TOPIC_NAME))

CREATE TABLE LANG(
	LANG_NAME VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY (LANG_NAME))

CREATE TABLE INSTITUTE(
	INSTITUTE_NAME VARCHAR(100) NOT NULL UNIQUE,
	UNIVERSITY_NAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (INSTITUTE_NAME, UNIVERSITY_NAME),
	FOREIGN KEY (UNIVERSITY_NAME) REFERENCES UNIVERSITY(UNIVERSITY_NAME)) 

CREATE TABLE THESIS(
	THESIS_NO NUMERIC(7,0) NOT NULL,
	TITLE VARCHAR(500) NOT NULL,
	ABSTRACT VARCHAR(5000) NOT NULL,
	AUTHOR_ID INT NOT NULL,
	YEAR INT NOT NULL,
	TYPE VARCHAR(100) NOT NULL
		CHECK(TYPE IN ('Master', 'Doctorate', 'Specialization in Medicine','Proficiency in Art')),
	UNIVERSITY_NAME VARCHAR(100) NOT NULL,
	INSTITUTE_NAME VARCHAR(100) NOT NULL,
	PAGES INT NOT NULL,
	LANGUAGE_NAME VARCHAR(50) NOT NULL,
	SUB_DATE DATE NOT NULL,
	PRIMARY KEY (THESIS_NO),
	FOREIGN KEY (AUTHOR_ID) REFERENCES PERSON(PERSON_ID),
    FOREIGN KEY (INSTITUTE_NAME, UNIVERSITY_NAME) REFERENCES INSTITUTE(INSTITUTE_NAME, UNIVERSITY_NAME),
	FOREIGN KEY (LANGUAGE_NAME) REFERENCES LANG(LANG_NAME))


CREATE TABLE SUPERVISOR(
	THESIS_NO NUMERIC(7,0) NOT NULL,
	SUPERVISOR_ID INT NOT NULL,
	COSUPERVISOR_ID INT,
	PRIMARY KEY (THESIS_NO),
	FOREIGN KEY (THESIS_NO) REFERENCES THESIS(THESIS_NO),
    FOREIGN KEY (SUPERVISOR_ID) REFERENCES PERSON(PERSON_ID),
    FOREIGN KEY (COSUPERVISOR_ID) REFERENCES PERSON(PERSON_ID),
	CONSTRAINT S_CS_DIFF CHECK (SUPERVISOR_ID <> COSUPERVISOR_ID))

CREATE TABLE THESIS_TOPIC(
	THESIS_NO NUMERIC(7,0) NOT NULL,
	TOPIC_NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY(THESIS_NO, TOPIC_NAME),
	FOREIGN KEY (THESIS_NO) REFERENCES THESIS(THESIS_NO),
    FOREIGN KEY (TOPIC_NAME) REFERENCES SUBJECT_TOPIC(TOPIC_NAME))

CREATE TABLE THESIS_KEYWORD(
	THESIS_NO NUMERIC(7,0) NOT NULL,
	KEYWORD VARCHAR(50),
	PRIMARY KEY (THESIS_NO, KEYWORD),
	FOREIGN KEY (THESIS_NO) REFERENCES THESIS(THESIS_NO))