USE GTS
DELETE FROM INSTITUTE
DELETE FROM LANG
DELETE FROM PERSON
DELETE FROM SUBJECT_TOPIC
DELETE FROM SUPERVISOR
DELETE FROM THESIS
DELETE FROM THESIS_KEYWORD
DELETE FROM THESIS_TOPIC
DELETE FROM UNIVERSITY

DBCC CHECKIDENT ('UNIVERSITY', RESEED, 0);
DBCC CHECKIDENT ('SUBJECT_TOPIC', RESEED, 0);
DBCC CHECKIDENT ('LANG', RESEED, 0)
DBCC CHECKIDENT ('INSTITUTE', RESEED, 0);
DBCC CHECKIDENT ('LANG', RESEED, 0);